---
- name: Listen for events on a kafka topic
  hosts: localhost
  sources:
   - ansible.eda.kafka:
      topic: "{{ kafka_topic | default('first_topic') }}"
      host: "{{ kafka_url | default('localhost') }}"
      port: "{{ kafka_port | default('9092') }}"
  rules:
   - name: Alert dropping signal
     condition:
       all:
         - event.body.signal < 10
         - event.body.signal < 9
         - event.body.signal < 8
       timeout: 30 seconds
     action:
       debug:
        msg:
          - "Signal is dropping"
   - name: Test rule
     condition: event.body != ''
     action:
       debug:
        msg:
          - "{{ event.body }}"
   - name: Test event rule
     condition: event.body.signal == 10
     action:
       debug:
        msg:
          - "Rulebook fired on event body"